//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOTING_SYSTEM_SERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bulletin
    {
        public int ID_Bulletin { get; set; }
        public int Candidate_Voting_ID { get; set; }
        public int Vote { get; set; }
        public int Users_ID { get; set; }
    
        public virtual Candidate_Voting Candidate_Voting { get; set; }
        public virtual User User { get; set; }
    }
}
