
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VOTING_SYSTEM_SERVER
{

using System;
    using System.Collections.Generic;
    
public partial class Candidate_Voting
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Candidate_Voting()
    {

        this.Bulletins = new HashSet<Bulletin>();

    }


    public int ID_Candidate_Voting { get; set; }

    public int Candidate_ID { get; set; }

    public int Voting_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bulletin> Bulletins { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual Voting Voting { get; set; }

}

}
