
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VOTING_SYSTEM_SERVER
{

using System;
    using System.Collections.Generic;
    
public partial class Candidate
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Candidate()
    {

        this.Candidate_Voting = new HashSet<Candidate_Voting>();

    }


    public int ID_Candidate { get; set; }

    public string Name { get; set; }

    public System.DateTime BirthDay { get; set; }

    public string Employment { get; set; }

    public string Programm { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Candidate_Voting> Candidate_Voting { get; set; }

}

}
