

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VOTING_SYSTEM_SERVER
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class voting_systemEntities : DbContext
{
    public voting_systemEntities()
        : base("name=voting_systemEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Bulletin> Bulletins { get; set; }

    public virtual DbSet<Candidate> Candidates { get; set; }

    public virtual DbSet<Candidate_Voting> Candidate_Voting { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Voting> Votings { get; set; }

}

}

