
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VOTING_SYSTEM_SERVER
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.Bulletins = new HashSet<Bulletin>();

    }


    public int ID_User { get; set; }

    public string Name { get; set; }

    public int PassportSeries { get; set; }

    public int PassportNumber { get; set; }

    public string WhoGives { get; set; }

    public System.DateTime WhenGives { get; set; }

    public Nullable<bool> isAdmin { get; set; }

    public string Password { get; set; }

    public string Token { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bulletin> Bulletins { get; set; }

}

}
