//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOTING_SYSTEM_CLIENT.VOTING_SERVER {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VOTING_SERVER.IVotingSystem")]
    public interface IVotingSystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetCandidateInfo", ReplyAction="http://tempuri.org/IVotingSystem/GetCandidateInfoResponse")]
        string GetCandidateInfo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetCandidateInfo", ReplyAction="http://tempuri.org/IVotingSystem/GetCandidateInfoResponse")]
        System.Threading.Tasks.Task<string> GetCandidateInfoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetCandidatesList", ReplyAction="http://tempuri.org/IVotingSystem/GetCandidatesListResponse")]
        string GetCandidatesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetCandidatesList", ReplyAction="http://tempuri.org/IVotingSystem/GetCandidatesListResponse")]
        System.Threading.Tasks.Task<string> GetCandidatesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/AddUser", ReplyAction="http://tempuri.org/IVotingSystem/AddUserResponse")]
        string AddUser(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/AddUser", ReplyAction="http://tempuri.org/IVotingSystem/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/Login", ReplyAction="http://tempuri.org/IVotingSystem/LoginResponse")]
        string Login(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/Login", ReplyAction="http://tempuri.org/IVotingSystem/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/SetVoiceForCandidate", ReplyAction="http://tempuri.org/IVotingSystem/SetVoiceForCandidateResponse")]
        void SetVoiceForCandidate(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/SetVoiceForCandidate", ReplyAction="http://tempuri.org/IVotingSystem/SetVoiceForCandidateResponse")]
        System.Threading.Tasks.Task SetVoiceForCandidateAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/CreateVoting", ReplyAction="http://tempuri.org/IVotingSystem/CreateVotingResponse")]
        string CreateVoting(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/CreateVoting", ReplyAction="http://tempuri.org/IVotingSystem/CreateVotingResponse")]
        System.Threading.Tasks.Task<string> CreateVotingAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetVoicesCountInVoting", ReplyAction="http://tempuri.org/IVotingSystem/GetVoicesCountInVotingResponse")]
        string GetVoicesCountInVoting(string data, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetVoicesCountInVoting", ReplyAction="http://tempuri.org/IVotingSystem/GetVoicesCountInVotingResponse")]
        System.Threading.Tasks.Task<string> GetVoicesCountInVotingAsync(string data, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVotingSystemChannel : VOTING_SYSTEM_CLIENT.VOTING_SERVER.IVotingSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VotingSystemClient : System.ServiceModel.ClientBase<VOTING_SYSTEM_CLIENT.VOTING_SERVER.IVotingSystem>, VOTING_SYSTEM_CLIENT.VOTING_SERVER.IVotingSystem {
        
        public VotingSystemClient() {
        }
        
        public VotingSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VotingSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VotingSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VotingSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCandidateInfo(string id) {
            return base.Channel.GetCandidateInfo(id);
        }
        
        public System.Threading.Tasks.Task<string> GetCandidateInfoAsync(string id) {
            return base.Channel.GetCandidateInfoAsync(id);
        }
        
        public string GetCandidatesList() {
            return base.Channel.GetCandidatesList();
        }
        
        public System.Threading.Tasks.Task<string> GetCandidatesListAsync() {
            return base.Channel.GetCandidatesListAsync();
        }
        
        public string AddUser(string user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(string user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public string Login(string data) {
            return base.Channel.Login(data);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string data) {
            return base.Channel.LoginAsync(data);
        }
        
        public void SetVoiceForCandidate(string data) {
            base.Channel.SetVoiceForCandidate(data);
        }
        
        public System.Threading.Tasks.Task SetVoiceForCandidateAsync(string data) {
            return base.Channel.SetVoiceForCandidateAsync(data);
        }
        
        public string CreateVoting(string data) {
            return base.Channel.CreateVoting(data);
        }
        
        public System.Threading.Tasks.Task<string> CreateVotingAsync(string data) {
            return base.Channel.CreateVotingAsync(data);
        }
        
        public string GetVoicesCountInVoting(string data, string token) {
            return base.Channel.GetVoicesCountInVoting(data, token);
        }
        
        public System.Threading.Tasks.Task<string> GetVoicesCountInVotingAsync(string data, string token) {
            return base.Channel.GetVoicesCountInVotingAsync(data, token);
        }
    }
}
