//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voiting_System_App.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVotingSystem")]
    public interface IVotingSystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetCandidateInfo", ReplyAction="http://tempuri.org/IVotingSystem/GetCandidateInfoResponse")]
        string GetCandidateInfo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetCandidatesList", ReplyAction="http://tempuri.org/IVotingSystem/GetCandidatesListResponse")]
        string GetCandidatesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/AddUser", ReplyAction="http://tempuri.org/IVotingSystem/AddUserResponse")]
        string AddUser(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/Login", ReplyAction="http://tempuri.org/IVotingSystem/LoginResponse")]
        string Login(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/SetVoiceForCandidate", ReplyAction="http://tempuri.org/IVotingSystem/SetVoiceForCandidateResponse")]
        void SetVoiceForCandidate(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/CreateVoting", ReplyAction="http://tempuri.org/IVotingSystem/CreateVotingResponse")]
        string CreateVoting(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVotingSystem/GetVoicesCountInVoting", ReplyAction="http://tempuri.org/IVotingSystem/GetVoicesCountInVotingResponse")]
        string GetVoicesCountInVoting(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVotingSystemChannel : Voiting_System_App.ServiceReference1.IVotingSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VotingSystemClient : System.ServiceModel.ClientBase<Voiting_System_App.ServiceReference1.IVotingSystem>, Voiting_System_App.ServiceReference1.IVotingSystem {
        
        public VotingSystemClient() {
        }
        
        public VotingSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VotingSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VotingSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VotingSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCandidateInfo(string id) {
            return base.Channel.GetCandidateInfo(id);
        }
        
        public string GetCandidatesList() {
            return base.Channel.GetCandidatesList();
        }
        
        public string AddUser(string user) {
            return base.Channel.AddUser(user);
        }
        
        public string Login(string data) {
            return base.Channel.Login(data);
        }
        
        public void SetVoiceForCandidate(string data) {
            base.Channel.SetVoiceForCandidate(data);
        }
        
        public string CreateVoting(string data) {
            return base.Channel.CreateVoting(data);
        }
        
        public string GetVoicesCountInVoting(string data) {
            return base.Channel.GetVoicesCountInVoting(data);
        }
    }
}
