//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceVoiting
{
    using System;
    using System.Collections.Generic;
    
    public partial class bulletin
    {
        public int id_bulletin { get; set; }
        public int candidate_voiting_id { get; set; }
        public bool vote { get; set; }
        public int user_id { get; set; }
    
        public virtual candidate_voiting candidate_voiting { get; set; }
        public virtual users users { get; set; }
    }
}
