//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceVoiting
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.bulletin = new HashSet<bulletin>();
        }
    
        public int id_user { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string fio { get; set; }
        public System.DateTime birthday { get; set; }
        public int seria_number { get; set; }
        public string who_gives { get; set; }
        public System.DateTime when_gives { get; set; }
        public bool is_admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bulletin> bulletin { get; set; }
    }
}
